### ISSUE TITLE
media

### ISSUE THREAD

**Issue by dchinmay2** [p00f/clangd_extensions.nvim#1]
![clangd](https://user-images.githubusercontent.com/36493671/152692205-837ec826-54d0-4257-9894-cc1a7ac8a114.svg)

**Comment by p00f** [comment]
![typehierarchy](https://github.com/p00f/clangd_extensions.nvim/assets/36493671/80bebd4a-9800-432d-9f0c-5e5519eeba6f)

**Comment by p00f** [comment]
![viewast](https://github.com/p00f/clangd_extensions.nvim/assets/36493671/35f397d3-02f8-4d14-b70a-126be6c098fa)
