### ISSUE TITLE
I use the default config, and Inlay hints doesn't work

### ISSUE THREAD

**Issue by SongTianxian9** [p00f/clangd_extensions.nvim#10]
NVIM v0.7.0-dev+1082-g046950f63
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by 

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-046950f/share/nvim"

Run :checkhealth for more info

![image](https://user-images.githubusercontent.com/88336105/153977042-390a96ee-ecd6-46b7-be28-7d712aa14168.png)
![image](https://user-images.githubusercontent.com/88336105/153977054-8c3692e5-c2f7-45be-95b3-1fdce77b9e46.png)

**Comment by p00f** [comment]
If you're using the default config you can skip the `extensions` part entirely, just configure the `server` setting

**Comment by p00f** [comment]
Do other things like symbol info work? (Put your cursor on a variable and run `:ClangdSymbolInfo`)

**Comment by SongTianxian9** [comment]
> Do other things like symbol info work? (Put your cursor on a variable and run `:ClangdSymbolInfo`)

they are work, just Inlay hints doesn't work

**Comment by p00f** [comment]
Hmmm

**Comment by SongTianxian9** [comment]
> If you're using the default config you can skip the `extensions` part entirely, just configure the `server` setting

i put them here just make sure i can change this config as i need, i try to delete them, and still does not work.
just Inlay hints does not work, others things work well. Maybe it's related to my colorscheme? I'm using [onedark](https://github.com/navarasu/onedark.nvim)

**Comment by SongTianxian9** [comment]
> 你的clangd版本是什么？

Apple clangd version 13.0.0 (clang-1300.0.29.30)

**Comment by p00f** [comment]
I think clangd also has a startup argument for inlay hints, can you try that.

**Comment by SongTianxian9** [comment]
> I think clangd also has a startup argument for inlay hints, can you try that?
> 
> Because https://clangd.llvm.org/extensions#inlay-hints says clangd 14 and it works for me with clangd 13 on Linux, so it might be experimentally enabled on 13 just for Linux

unbelievable, I reinstalled clangd with homebrew "brew install llvm", now inlay hints work for me!! thanks for you gays replay!
`Homebrew clangd version 13.0.1
Features: mac+xpc
Platform: x86_64-apple-darwin21.3.0`

**Comment by cxzhou35** [comment]
How to set the inlay hints at the neovim startup? @p00f 
Here is my config:
```lua
return {
  "p00f/clangd_extensions.nvim",
  lazy = true,
  config = function() end,
  opts = {
    inlay_hints = {
      inline = false,
      show_parameter_hints = true,
    },
    ast = {
      --These require codicons (https://github.com/microsoft/vscode-codicons)
      role_icons = {
        type = "",
        declaration = "",
        expression = "",
        specifier = "",
        statement = "",
        ["template argument"] = "",
      },
      kind_icons = {
        Compound = "",
        Recovery = "",
        TranslationUnit = "",
        PackExpansion = "",
        TemplateTypeParm = "",
        TemplateTemplateParm = "",
        TemplateParamObject = "",
      },
    },
  },
}

The inlay hints can work when I use the `ClangdSetInlayHints` command, but I want to the inlay hints auto start at the startup time, any solution to that?
```

**Comment by p00f** [comment]
@cxzhou35 https://github.com/p00f/clangd_extensions.nvim#usage

**Comment by cxzhou35** [comment]
> @cxzhou35 https://github.com/p00f/clangd_extensions.nvim#usage

Sorry, I am not familar with the nvim-lspconfig, how to add the config?
