### ISSUE TITLE
lsp installer

### ISSUE THREAD

**Issue by bryant-the-coder** [p00f/clangd_extensions.nvim#14]
how can i use this with lsp installer? when i follow the readme, error shows up

![image](https://user-images.githubusercontent.com/92417638/160384909-0c9a531b-32b4-4725-ad4e-82113962cbf4.png)

**Comment by bryant-the-coder** [comment]
https://github.com/bryant-the-coder/NvHack/blob/main/lua/plugins/config/lsp/settings/clang.lua

**Comment by p00f** [comment]
install https://github.com/neovim/nvim-lspconfig

**Comment by bryant-the-coder** [comment]
hey uhm. i am getting this strange warning saying that theylre are multiple encoding for currect buffer. how can i solve that?

**Comment by p00f** [comment]
No idea, ask in the matrix room

**Comment by bryant-the-coder** [comment]
matrix room? where?

**Comment by p00f** [comment]
#neovim:matrix.org
