### ISSUE TITLE
move parameter hints aside the parameter value

### ISSUE THREAD

**Issue by lmascelli** [p00f/clangd_extensions.nvim#20]
Hello, is it possible to have the hint of the parameter name aside the given value?
Es. 
f(a: 5, b: 3, c: 4)
instead of 
f(5, 3, 4) <- (a, b, c)

thanks

**Comment by p00f** [comment]
Not until https://github.com/neovim/neovim/pull/9496

**Comment by p00f** [comment]
Will reopen once neovim/neovim#9496 is merged
