### ISSUE TITLE
nvim 0.10 inlay hints broken

### ISSUE THREAD

**Issue by barrett-ruth** [p00f/clangd_extensions.nvim#37]
I see in a recent commit you added support for nvim 0.10 inlay hints.

On the event `LspAttach` with clangd, the field `client.server_capabilities.inlayHintProvider` is not set to true. However, `clangdInlayHintsProvider` is - I think clangd may be calling the inlay hint field something other than what the standard expects? Either way, the error stems from when a lsp request is sent in [this line](https://github.com/p00f/clangd_extensions.nvim/blob/6d0bf36870d15c0c2284f4b6693a66552a6bf127/lua/clangd_extensions/inlay_hints.lua#L297C33-L297C33) and the provider is not found in the LSP config.

I get the following error when opening up an empty c++ file in nvim 0.10:
<img width="758" alt="image" src="https://github.com/p00f/clangd_extensions.nvim/assets/62671086/1c15fa56-4645-4593-a5bf-4be431e3a2b0">

Let me know if I can provide more info or if you think my environment is set up incorrectly.

**Comment by barrett-ruth** [comment]
Also, notably, changing the `"textDocument/inlayHint"` back to `"clangd/inlayHints"` works like a charm:

<img width="221" alt="image" src="https://github.com/p00f/clangd_extensions.nvim/assets/62671086/bcd01a38-6443-4d42-952a-f79b3fb0001e">

**Comment by p00f** [comment]
You need to update clangd

**Comment by p00f** [comment]
In any case this is the wrong place if you're using LSP inlay hints - this plugin is only for off-spec features


To reiterate, either - 
1) Update clangd, use 0.10's LSP inlay hints and disable inlay hints in clangd_extensions.nvim
2) Use clangd_extensions.nvim and don't enable 0.10's LSP inlay hints

**Comment by barrett-ruth** [comment]
Thank you for explaining the issue clearly. Apologies for my misconceptions.
