### ISSUE TITLE
Weird indentation on enter

### ISSUE THREAD

**Issue by gabyx** [p00f/clangd_extensions.nvim#45]
I am using this plugin.
and a .clang-format in the root.
The formatting works normally over the LSP.

However when I press enter 
```cpp
{/*< cursor here/*}
```

the line then looks like

```cpp
{
␣␣␣␣␣␣␣␣/*<cursor here/*
␣␣␣␣}
```

I dont know where these indents on the last line come from? also the indentation on the line where the cursor is is not `4` spaces witch is set in the `.editorconfig` file.

This might not be related to the clangd extensions, but I am trying to figureing out where the problem comes from?
Do you might have any idea?

Thanks a lot

**Comment by p00f** [comment]
No idea
