### ISSUE TITLE
`inline = true, only_current_line = false` not working 

### ISSUE THREAD

**Issue by horror-proton** [p00f/clangd_extensions.nvim#48]
When using config with
```lua
inlay_hints = {inline = true, only_current_line = false}
```
inlay hints would only show up on current line after calling set_inlay_hints.

Using
- NVIM v0.10.0-dev-1042+gd272143318
- clangd version 16.0.6

-----

I think the problem might be here
https://github.com/p00f/clangd_extensions.nvim/blob/323b00de2ee18cad1ac45eb95e680386c4ff4366/lua/clangd_extensions/inlay_hints.lua#L266

It works normally after adding
```diff
-        if line == current_line - 1 then
+        if line == current_line - 1 or not config.options.inlay_hints.only_current_line then
```

**Comment by p00f** [comment]
Nice catch, thanks
