### ISSUE TITLE
Key mappings created by the `Type hierarchy` should support user configuration.

### ISSUE THREAD

**Issue by NGPONG** [p00f/clangd_extensions.nvim#51]
hi @p00f , thanks for this great plugin!

I'm used to keeping my keymaps clean in my workflow, so are you going to support this configuration? If you don't have time I can submit a PR, what do you think?

**Comment by p00f** [comment]
there's only one keymap, which is the standard `gd`. I don't want to support configuring - because `gd` is standard -  unless there is enough interest - for now, I'm closing this

**Comment by NGPONG** [comment]
Thank you for your response. Well, I'm going to have some quirks with the configuration, which makes me have to unmap these by some other _way_.
