### ISSUE TITLE
Exclude file from analysis

### ISSUE THREAD

**Issue by stexa** [p00f/clangd_extensions.nvim#52]
Is there a simple way of excluding a cpp file from analysis in the plugin or does this need to be done on the clangd level directly?

**Comment by p00f** [comment]
The latter - this plugin is simply for extra features not supported by neovim

**Comment by p00f** [comment]
fwiw I don't know of any way to do that, other than maybe detaching using a bufenter autocommand (which still might not exclude it from "analysis")

**Comment by stexa** [comment]
Thanks I will have a look!
