### ISSUE TITLE
[Off-topic] Slick cursor animation

### ISSUE THREAD

**Issue by SirWrexes** [p00f/clangd_extensions.nvim#53]
Hey,
I was looking into setting up this plugin to empower my C experience, but my eye caught something on the way.
How do you achieve those sick cursor movement animations ?
![](https://user-images.githubusercontent.com/36493671/255609950-80bebd4a-9800-432d-9f0c-5e5519eeba6f.gif)
Thanks~

**Comment by p00f** [comment]
That's a neovim GUI: https://github.com/neovide/neovide

**Comment by SirWrexes** [comment]
Ah so that's why it's so smooth, I was wondering.
That theme fooled me, though, it really has a term feel to it !
Thanks for your quick reply !
