### ISSUE TITLE
`ClangdToggleInlayHints` must hits twice first time

### ISSUE THREAD

**Issue by cxwx** [p00f/clangd_extensions.nvim#58]
when I use 
```
      local on_attach2 = function(_, bufnr)
        vim.api.nvim_buf_set_option(bufnr, "omnifunc", "v:lua.vim.lsp.omnifunc")
        require("clangd_extensions.inlay_hints").setup_autocmd()
        require("clangd_extensions.inlay_hints").set_inlay_hints()
      end

```
```
{
    "p00f/clangd_extensions.nvim",
    enabled = true,
    ft = { "c", "cpp" },
    opts = { extensions = { autoSetHints = true } },
    lazy = true,
}
```

the inlayHints auto start,
for the first time I use `ClangdToggleInlayHints`
I must entering the cmd twice.
Is there some where configure wrong with me？

**Comment by p00f** [comment]
You don't need to lazy load it, good plugins (including this one) lazy-load themselves.

If the issue still persists, please provide a minimal reproduction using a simpler plugin manager like [vim-plug](https://github.com/junegunn/vim-plug), [paq-nvim](https://github.com/savq/paq-nvim) or [`:h packages`](https://neovim.io/doc/user/repeat.html#packages)

**Comment by p00f** [comment]
Author has not responded, closing
