### ISSUE TITLE
Inlay hints don't update after editting text, only after saving file

### ISSUE THREAD

**Issue by h3xOo** [p00f/clangd_extensions.nvim#59]
If I have code snippet like this: 
![obraz](https://github.com/p00f/clangd_extensions.nvim/assets/82811246/f6e2d86a-581f-47af-a3fb-34065325cf96)
and edit string inside it, I'm left with inlay hints on right:
![obraz](https://github.com/p00f/clangd_extensions.nvim/assets/82811246/29f1d419-c135-47fa-ad9f-2db160072975)
After `:w` they are fine.
And also after `dd`-ing line, hints stick to line below with doubled indentation (again, `:w` fixes the issue):
![obraz](https://github.com/p00f/clangd_extensions.nvim/assets/82811246/b1ad9dec-fe73-4746-a1b0-b213b6dcd1ad)

**Comment by p00f** [comment]
yes, this is intentionally simple -

https://github.com/p00f/clangd_extensions.nvim/blob/f36d788f05cfb73d4fd2e606e6ad15f8b842124f/lua/clangd_extensions/inlay_hints.lua#L31

to get correctly updating inlay hints, disable inlay hints in clangd_extensions.nvim and use [`:h vim.lsp.inlay_hint`](https://neovim.io/doc/user/lsp.html#lsp-inlay_hint)

**Comment by p00f** [comment]
I'll remove this feature from clangd extensions after some time, now that it has landed in neovim itself
