### ISSUE TITLE
Clangd Include files

### ISSUE THREAD

**Issue by gGameDevelop** [p00f/clangd_extensions.nvim#68]
### How i can add an include directories for every cpp project
after i setup neovim with mason and clangd the intelesence and the code complition was working correctly but how i can add include directories for using libraries in clangd neovim.

**Comment by p00f** [comment]
Use your build system to generate a compile_commands.json, search "<build system> compile_commands.json" where "build system" is whatever you're using (cmake, meson, bazel etc)

If you're using just makefiles then use bear

**Comment by gGameDevelop** [comment]
I m using cmake, but i need the intelesence to auto complite like glfw3 functions and ENUMs by including <GLFW/glfw3>
##### "i want it to know wher is the include file"
and get all the methods so if i want to use glfw or any library, the intelesence say that is no definition for that function.

this is just for working in the project not for building if i want to build i can add the libraries including files for the compilation process so the compiler know that the function definition is here and no need to return the unexist method

**Comment by p00f** [comment]
Yes, you need to `cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON` then build the project for this to work.

> this is just for working in the project not for building

yes, i know what i'm talking about

**Comment by gGameDevelop** [comment]
thanks.
