### ISSUE TITLE
Make AST symbols configurable

### ISSUE THREAD

**Issue by chen244** [p00f/clangd_extensions.nvim#7]
Which font you use ,When I use ClangAst, I can not view icon.

The font I am using is firacode nerd font mono

**Comment by chen244** [comment]
https://github.com/p00f/clangd_extensions.nvim/blob/main/lua/clangd_extensions/ast.lua#L24

These Icon cannot shown for me

**Comment by p00f** [comment]
https://github.com/microsoft/vscode-codicons

I intend to make these configurable, don't worry

**Comment by p00f** [comment]
The default config now uses unicode icons which should be available in any font

https://github.com/p00f/clangd_extensions.nvim/commit/f2ca89d978f9fc907beb432a472a89fced7e10bd
